#!/usr/bin/env python3
"""
Gemini Vision API for JARVIS Visual Analysis
Provides image analysis capabilities for the JARVIS voice assistant
"""

import os
import base64
import json
from typing import Optional, Dict, Any
import google.generativeai as genai
from PIL import Image
import io

class GeminiVisionAPI:
    def __init__(self, api_key: Optional[str] = None):
        """Initialize Gemini Vision API"""
        self.api_key = api_key or os.getenv('GEMINI_API_KEY')
        if not self.api_key:
            raise ValueError("Gemini API key not found. Set GEMINI_API_KEY environment variable.")
        
        # Configure Gemini
        genai.configure(api_key=self.api_key)
        
        # Initialize the vision model
        self.model = genai.GenerativeModel('gemini-1.5-flash')
        
        print("✅ Gemini Vision API initialized")
    
    def analyze_image(self, image_data: str, prompt: str = None) -> Dict[str, Any]:
        """
        Analyze an image using Gemini Vision
        
        Args:
            image_data: Base64 encoded image data
            prompt: Optional custom prompt for analysis
            
        Returns:
            Dictionary with analysis results
        """
        try:
            # Default JARVIS analysis prompt
            if not prompt:
                prompt = """You are JARVIS, Tony Stark's AI assistant. Analyze this image and identify what's visible.

Focus on:
1. Main objects or components in the image
2. Technical details if it's engineering/CAD content  
3. 3D models, mechanical parts, or technical elements
4. Any specific parts or features that stand out

Respond as JARVIS would - sophisticated, detailed, and helpful. Be specific about what you observe."""

            # Decode base64 image
            try:
                image_bytes = base64.b64decode(image_data)
                image = Image.open(io.BytesIO(image_bytes))
                print(f"📸 Image loaded: {image.size} pixels, mode: {image.mode}")
            except Exception as e:
                return {
                    "status": "error",
                    "error": f"Failed to decode image: {str(e)}"
                }
            
            # Generate analysis
            print("🧠 Sending image to Gemini Vision for analysis...")
            response = self.model.generate_content([prompt, image])
            
            if not response.text:
                return {
                    "status": "error", 
                    "error": "No analysis generated by Gemini Vision"
                }
            
            analysis = response.text.strip()
            print(f"✅ Analysis complete: {len(analysis)} characters")
            
            return {
                "status": "success",
                "analysis": analysis,
                "image_info": {
                    "size": image.size,
                    "mode": image.mode,
                    "format": image.format
                }
            }
            
        except Exception as e:
            error_message = str(e)
            print(f"❌ Error in image analysis: {error_message}")
            
            # Check for specific error types
            if "429" in error_message or "quota" in error_message.lower():
                return {
                    "status": "error",
                    "error": "API quota exceeded. Please wait or upgrade your Gemini API plan.",
                    "error_type": "quota_exceeded"
                }
            elif "401" in error_message or "unauthorized" in error_message.lower():
                return {
                    "status": "error", 
                    "error": "API key invalid or unauthorized.",
                    "error_type": "auth_error"
                }
            else:
                return {
                    "status": "error",
                    "error": error_message,
                    "error_type": "general_error"
                }
    
    def analyze_screenshot_for_jarvis(self, image_data: str) -> Dict[str, Any]:
        """
        Specialized analysis for JARVIS screenshot analysis
        
        Args:
            image_data: Base64 encoded screenshot data
            
        Returns:
            Dictionary with JARVIS-formatted analysis
        """
        jarvis_prompt = """You are JARVIS, Tony Stark's sophisticated AI assistant. I'm showing you a screenshot of what I'm currently viewing.

ANALYSIS REQUIREMENTS:
1. Identify the main subject or object in the image
2. If it's a 3D model, CAD design, or technical component - explain what it is
3. Focus on any prominent features, parts, or details
4. If someone appears to be pointing at something, identify what they're pointing at
5. Provide technical context if it's engineering/mechanical content

RESPONSE STYLE:
- Speak as JARVIS with British sophistication
- Be precise and informative
- Use technical terminology when appropriate  
- Keep it concise but thorough
- Address me as "Sir" or "Mr. Stark"

What do you observe in this image, JARVIS?"""

        return self.analyze_image(image_data, jarvis_prompt)
    
    def health_check(self) -> Dict[str, Any]:
        """Check if the API is working properly"""
        try:
            # Test with a simple prompt
            test_prompt = "Say 'JARVIS Vision API is operational, Sir.'"
            response = self.model.generate_content(test_prompt)
            
            if response.text:
                return {
                    "status": "healthy",
                    "message": "Gemini Vision API is operational",
                    "test_response": response.text.strip()
                }
            else:
                return {
                    "status": "error",
                    "message": "No response from Gemini Vision API"
                }
                
        except Exception as e:
            return {
                "status": "error", 
                "message": f"Health check failed: {str(e)}"
            }

# Flask integration for web API
def create_vision_api_routes(app, vision_api: GeminiVisionAPI):
    """Create Flask routes for the vision API"""
    
    @app.route('/api/gemini/vision-analyze', methods=['POST'])
    def analyze_image_endpoint():
        try:
            data = request.get_json()
            
            if not data or 'image' not in data:
                return jsonify({
                    "status": "error",
                    "error": "No image data provided"
                }), 400
            
            image_data = data['image']
            prompt = data.get('prompt', None)
            
            # Perform analysis
            result = vision_api.analyze_image(image_data, prompt)
            
            return jsonify(result)
            
        except Exception as e:
            return jsonify({
                "status": "error",
                "error": str(e)
            }), 500
    
    @app.route('/api/gemini/vision-health', methods=['GET'])
    def vision_health_check():
        try:
            result = vision_api.health_check()
            status_code = 200 if result['status'] == 'healthy' else 500
            return jsonify(result), status_code
            
        except Exception as e:
            return jsonify({
                "status": "error",
                "error": str(e)
            }), 500

# Standalone testing
if __name__ == "__main__":
    import sys
    
    # Test the vision API
    try:
        vision_api = GeminiVisionAPI()
        
        # Health check
        health = vision_api.health_check()
        print("🏥 Health check:", health)
        
        # Test with sample image if provided
        if len(sys.argv) > 1:
            image_path = sys.argv[1]
            if os.path.exists(image_path):
                with open(image_path, 'rb') as f:
                    image_data = base64.b64encode(f.read()).decode('utf-8')
                
                result = vision_api.analyze_screenshot_for_jarvis(image_data)
                print("🔍 Analysis result:", json.dumps(result, indent=2))
            else:
                print(f"❌ Image file not found: {image_path}")
        
    except Exception as e:
        print(f"❌ Error testing vision API: {e}")
